name: Reproduce push error
on:
  push:
    branches:
    - km/reproduce-push-error-11.5.0

permissions: {}

jobs:
  push-and-pr:
    if: github.repository == 'grafana/grafana'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Grafana
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-tags: true
          fetch-depth: 0
      - name: Configure git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local --add --bool push.autoSetupRemote true
          git checkout km/reproduce-push-error-11.5.0
          git checkout -b "km/${{ github.run_id }}"
      - run: |
          touch new-file.txt
          git add new-file.txt && git commit --allow-empty -m "Add new file (testing)"
      - name: Git push
        run: git push
      - name: Create PR without backports
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            -l "no-changelog" \
            -B "km/${{ github.run_id }}" \
            --dry-run=true \
            --base "km/reproduce-push-error" \
            --title "[Testing (@joshhunt)] Testing automation push error" \
            --body "Ignore this, testing pushes from automation for support ticket because of all of the backport.yml failures"
